parameters:
#    pxl_ctzn_home.example.class: PxlCtzn\HomeBundle\Example

services:
#    pxl_ctzn_home.example:
#        class: %pxl_ctzn_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
