parameters:
#    pxl_ctzn_blog.example.class: PxlCtzn\BlogBundle\Example

services:
#    pxl_ctzn_blog.example:
#        class: %pxl_ctzn_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
